Correct off by one error with the range header.
The range header includes the `0` byte; so a 5 byte payload has a range
of `0-4`.

As per https://github.com/moby/buildkit/issues/2568 and
https://github.com/docker/for-linux/issues/1296, the header being off by
one is an issue when using BuildKit's buildctl command as the manifest
contains the wrong size - being one too large which then fails when
trying to read one byte too many from the image.

The issue can be seen when viewing the manifest in the registry data:

In the layers payload:

```
  ...
  "size": 894478744,
  "digest": "sha256:929d4d417adbdafe947076e47161e10f88afcb63716ff7ec3205bc8f62be085f"
```

Whilst a `du -b` of the blob
`929d4d417adbdafe947076e47161e10f88afcb63716ff7ec3205bc8f62be085f` is
actually `894478743`.

The error doesn't present when using the Docker daemon to build (using
BuildKit or not) as it doesn't check this size. It needs to be the
buildctl directly.

Note that buildctl caches the manifest data from the first place the
image was pulled from, so pulling from a broken registry and then an
unbroken one; the build will still fail. The error in buildctl is:

```
/moby.buildkit.v1.Control/Solve returned error: rpc error: code = Unknown desc = failed to compute cache key: failed to read expected number of bytes: unexpected EOF
```

Or

```
error: failed to solve: failed to compute cache key: failed commit on ref "layer-sha256:929d4d417adbdafe947076e47161e10f88afcb63716ff7ec3205bc8f62be085f": "layer-sha256:929d4d417adbdafe947076e47161e10f88afcb63716ff7ec3205bc8f62be085f" failed size validation: 894478743 != 894478744: failed precondition
```

Depending on the version of buildctl.